name = "summarize-text"
main = "src/main.ts"
compatibility_date = "2024-01-01"

[vars]
OPENAI_API_DEFAULT_URL = "https://api.openai.com/v1/chat/completions"
OPENAI_DEFAULT_MODEL = "gpt-4o"

[observability]
enabled = true
head_sampling_rate = 1
